# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    -   id: black
        exclude: ^(.+)/migrations/.*\.py
        
