version: "3.9"

services:
  wachterbot:
    container_name: wachterbot-prod
    image: ghcr.io/alexeyqu/wachter_bot/wachterbot:prod
    volumes:
      - type: bind
        source: /home/github/prod/jobs.json
        target: /app/jobs.json
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - UPTRACE_DSN=${UPTRACE_DSN}
      - TELEGRAM_ERROR_CHAT_ID=${TELEGRAM_ERROR_CHAT_ID}
      - DATABASE_URL=${DATABASE_URL}
      - PERSISTENCE_DATABASE_URL=${PERSISTENCE_DATABASE_URL}
      - DEBUG=${DEBUG}
      - DEPLOYMENT_ENVIRONMENT=production
      - TEAM_TELEGRAM_IDS=${TEAM_TELEGRAM_IDS}
    restart: unless-stopped

networks:
  default:
    name: network-wachterbot-prod
