"""create filter_only_new_users

Revision ID: 0336b796d052
Revises: 65330214bff4
Create Date: 2019-01-05 15:25:08.201425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0336b796d052"
down_revision = "65330214bff4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chats",
        sa.Column(
            "filter_only_new_users", sa.Boolean, nullable=False, server_default="False"
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chats", "filter_only_new_users")
    # ### end Alembic commands ###
