"""add regex filter

Revision ID: 65330214bff4
Revises: 2345e3de1ccc
Create Date: 2018-08-19 21:52:23.437227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "65330214bff4"
down_revision = "2345e3de1ccc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chats", sa.Column("regex_filter", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chats", "regex_filter")
    # ### end Alembic commands ###
