"""create new messages

Revision ID: ae0105c2205b
Revises: fd40280af78a
Create Date: 2018-07-04 20:05:09.847739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae0105c2205b'
down_revision = 'fd40280af78a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('notify_message', sa.Text(), nullable=False))
    op.add_column('chats', sa.Column('on_known_new_chat_member_message', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'on_known_new_chat_member_message')
    op.drop_column('chats', 'notify_message')
    # ### end Alembic commands ###
