name: Formatting check on pull requests

on:
  pull_request:
    branches:
      - dev

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    environment: 
      name: testing

    steps:
    - name: checkout repository
      uses: actions/checkout@v2

    - name: set up Python
      uses: actions/setup-python@v2

    - name: install pre-commit
      run: python -m pip install pre-commit
      shell: bash

    - name: pip freeze
      run: python -m pip freeze --local
      shell: bash
      
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v44
        
    - name: run pre-commit 
      run: |
          FILES="${{ steps.changed-files.outputs.all_changed_files }}"
          if [ -n "$FILES" ]; then
            echo "$FILES" | xargs pre-commit run --files
          else
            echo "No files to check."
          fi
      shell: bash
