name: Testing on pull requests

on:
  pull_request:
    branches:
      - dev

jobs:
  docker-compose-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # fetches all commits


    - name: Build and run docker compose
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_AUTOTEST_TOKEN }}
      run: |
        docker-compose -f docker-compose.dev.yml up -d 

    - name: Check docker logs for errors
      run: |
        # Sleep for 10 seconds to let the container initialize
        sleep 10
        logs=$(docker logs wachter-dev)
        if echo $logs | grep -i "exited with code"; then
          echo "Found errors in Docker logs"
          exit 1
        fi

    - name: Run black on changed files
      run: |
        # Get list of changed files
          BASE_SHA=$(git rev-parse origin/${GITHUB_BASE_REF})
          HEAD_SHA=$(git rev-parse origin/${GITHUB_HEAD_REF})
          FILES=$(git diff --name-only $BASE_SHA $HEAD_SHA | grep '\.py$' | grep -v '/migrations/' | tr '\n' ' ')

          echo "Changed files: $FILES"

          FILES_QUOTED=""
          for file in $FILES; do
            FILES_QUOTED="$FILES_QUOTED '$file'"
          done
          echo "Changed quoted files: $FILES_QUOTED"

        # Execute black inside container
          set -x
          docker exec wachter-dev bash -c "pipenv run black $FILES_QUOTED"
